"""Add is_landlord_approved field to User model

Revision ID: 156f7fd3026c
Revises: 9f871a39a2c0
Create Date: 2025-03-10 22:18:29.488800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156f7fd3026c'
down_revision = '9f871a39a2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_landlord_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_landlord_approved')

    # ### end Alembic commands ###
