"""Update tenant preferences schema with constraints

Revision ID: 4d404c481fac
Revises: 
Create Date: 2025-01-13 13:23:47.351212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d404c481fac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.alter_column('max_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('min_size',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('preferred_location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('required_amenities',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('safety_weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cleanliness_weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('accessibility_weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('noise_level_weight',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.alter_column('noise_level_weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('accessibility_weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cleanliness_weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('safety_weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('required_amenities',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('preferred_location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('min_size',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('max_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
