"""Add preferred_distance to TenantPreference

Revision ID: 60caa42967d5
Revises: a4033e22bb18
Create Date: 2025-03-09 12:39:09.622637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60caa42967d5'
down_revision = 'a4033e22bb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.drop_column('preferred_distance')

    # ### end Alembic commands ###
