"""Add document fields to Room model

Revision ID: 74451a03578b
Revises: email_verification_fields
Create Date: 2025-03-21 22:53:12.443166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74451a03578b'
down_revision = 'email_verification_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_unique_constraint('uq_user_verification_token', ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_verification_token', type_='unique')
        batch_op.alter_column('is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('document_name')
        batch_op.drop_column('document_url')

    # ### end Alembic commands ###
