"""Add tenant rating system

Revision ID: 960cd4bdae85
Revises: 73f6a69f7225
Create Date: 2025-02-08 16:09:29.590598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960cd4bdae85'
down_revision = '73f6a69f7225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('safety_rating', sa.Float(), nullable=False),
    sa.Column('cleanliness_rating', sa.Float(), nullable=False),
    sa.Column('accessibility_rating', sa.Float(), nullable=False),
    sa.Column('noise_level_rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'room_id', name='unique_tenant_room_rating')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_safety_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_cleanliness_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_accessibility_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_noise_level_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_ratings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('total_ratings')
        batch_op.drop_column('avg_noise_level_rating')
        batch_op.drop_column('avg_accessibility_rating')
        batch_op.drop_column('avg_cleanliness_rating')
        batch_op.drop_column('avg_safety_rating')

    op.drop_table('tenant_rating')
    # ### end Alembic commands ###
