"""Add approval status to Room model

Revision ID: 9f871a39a2c0
Revises: c1d1a3ed3110
Create Date: 2025-03-09 14:18:32.897819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f871a39a2c0'
down_revision = 'c1d1a3ed3110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), server_default='pending', nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
