"""make_amenity_rating_non_nullable

Revision ID: a393d0f5e423
Revises: f2f70bcc99a7
Create Date: 2025-03-23 15:16:07.700044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'a393d0f5e423'
down_revision = 'f2f70bcc99a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update all NULL amenity_rating values to a default of 5.0
    conn = op.get_bind()
    conn.execute(text("UPDATE tenant_rating SET amenity_rating = 5.0 WHERE amenity_rating IS NULL"))
    
    # Then make the column non-nullable
    with op.batch_alter_table('tenant_rating', schema=None) as batch_op:
        batch_op.alter_column('amenity_rating',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_rating', schema=None) as batch_op:
        batch_op.alter_column('amenity_rating',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
