"""change size to capacity in Room and TenantPreference models

Revision ID: eb55d30ab582
Revises: d3624e576dc1
Create Date: 2025-01-27 19:43:12.533842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb55d30ab582'
down_revision = 'd3624e576dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_room')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default='1', nullable=False))
        batch_op.drop_column('size')

    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_capacity', sa.Integer(), server_default='1', nullable=False))
        batch_op.drop_column('min_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_size', sa.FLOAT(), nullable=False))
        batch_op.drop_column('min_capacity')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.FLOAT(), nullable=True))
        batch_op.drop_column('capacity')

    op.create_table('_alembic_tmp_room',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_urls', sa.TEXT(), nullable=True),
    sa.Column('landlord_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('amenities', sa.TEXT(), nullable=True),
    sa.Column('availability', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('safety_score', sa.FLOAT(), nullable=True),
    sa.Column('cleanliness_score', sa.FLOAT(), nullable=True),
    sa.Column('accessibility_score', sa.FLOAT(), nullable=True),
    sa.Column('noise_level', sa.FLOAT(), nullable=True),
    sa.Column('capacity', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
