"""Add amenity rating field

Revision ID: f2f70bcc99a7
Revises: 74451a03578b
Create Date: 2025-03-23 14:56:16.680382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f70bcc99a7'
down_revision = '74451a03578b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenity_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_rating', schema=None) as batch_op:
        batch_op.drop_column('amenity_rating')

    # ### end Alembic commands ###
