"""Add living_space_type to tenant preferences

Revision ID: f89fef7f933c
Revises: 960cd4bdae85
Create Date: 2025-02-08 16:25:38.238927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89fef7f933c'
down_revision = '960cd4bdae85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('living_space_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_preference', schema=None) as batch_op:
        batch_op.drop_column('living_space_type')

    # ### end Alembic commands ###
